initial_cash: 1000.0
symbols:
  - BTC/USDT
  - ETH/USDT
  - SUI/USDT
interval: 15m
bb:
  length: 20
  std: 2
rsi:
  length: 14
risk:
  max_open_positions: 10
  stop_loss_pct: 0.05
  take_profit:
    tier1_pct: 0.01  # 1% first tier
    tier2_pct: 0.02  # 2% second tier
    tier3_pct: 0.03  # 3% third tier
    tier1_size_pct: 0.5  # Sell 50% at first tier
    tier2_size_pct: 0.5  # Sell 50% at second tier
    tier3_size_pct: 1  # Sell 100% at third tier (remaining)
  position_size_pct: 0.333  # % of equity per trade
  daily_loss_cap_pct: 0.05  # 5% daily loss triggers pause
cool_down:
  minutes: 15  # Minimum time between trades for same symbol

backtest:
  start_date: "2025-04-01" 
  end_date: "2025-04-09"
