version: "3.8"

services:
  crypton:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypton
    restart: unless-stopped

    # Bind‑mount configuration & persistent folders
    volumes:
      - ./config.yml:/home/crypton/app/config.yml
      - ./data:/home/crypton/data
      - ./logs:/home/crypton/logs

    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BINANCE_TESTNET_API_KEY=${BINANCE_TESTNET_API_KEY}
      - BINANCE_TESTNET_API_SECRET=${BINANCE_TESTNET_API_SECRET}
      - MODE=${MODE:-test}
      - SLACK_WEBHOOK=${SLACK_WEBHOOK}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-UTC}

    # Default command (overrides Dockerfile CMD)
    #command: trade --mode ${MODE:-test} --config /home/crypton/app/config.yml
    command: paper --config /home/crypton/app/config.yml